spring:
  data:
    rest:
      base-path: /api
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./tmpdb/h2db
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect

management:
  security:
    enabled: false
  server:
    port: 9000